[tool.poetry]
name = "amex"
version = "0.1.0"
description = "Code for Kaggle competition for amex-default-prediction"
authors = [
    "Najib Ishaq <najib_ishaq@zoho.com>",
]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"